from env import (
    _MOVE_FWD_,
    _MOVE_BCK_,
    _MOVE_LEFT_,
    _MOVE_RIGHT_,
    _PAN_LEFT_,
    _PAN_RIGHT_,
    _TILT_UP_,
    _TILT_DOWN_,
    _XTNFWD_LEFT_,
    _PLLBCK_LEFT_,
    _XTNFWD_RIGHT_,
    _PLLBCK_RIGHT_,
    _GRIP_LEFT_,
    _GRIP_RIGHT_,
)

actions_ref = {
    'MOVE_FWD': _MOVE_FWD_,
    'MOVE_BACK': _MOVE_BCK_,
    'MOVE_LEFT': _MOVE_LEFT_,
    'MOVE_RIGHT': _MOVE_RIGHT_,
    'PAN_LEFT': _PAN_LEFT_,
    'PAN_RIGHT': _PAN_RIGHT_,
    'TILT_UP': _TILT_UP_,
    'TILT_DOWN': _TILT_DOWN_,
    'EXTEND_LEFT': _XTNFWD_LEFT_,
    'PULL_LEFT': _PLLBCK_LEFT_,
    'EXTEND_RIGHT': _XTNFWD_RIGHT_,
    'PULL_RIGHT': _PLLBCK_RIGHT_,
    'GRIP_LEFT': _GRIP_LEFT_,
    'GRIP_RIGHT': _GRIP_RIGHT_,
}