# # ========= Layout 1 =========
# BASE_SEMANTIC_MEMORY = ("This semantic memory outlines the store's environment, detailing its layout, item locations, and general product descriptions.\n\n"
#                         "**Layout of the Store**:\n"
#                         "1. Counter: Situated near Shelf 1, this area includes a cash register.\n"
#                         "2. Shelf 1: Features a variety of snacks and junk food, including Pringles, potato chips, cheese rings, Tostitos, Clover Chips, corn chips, Prawn Crackers, Kang-Kong Chips, and Pik-Nik Shoestring Potatoes.\n"
#                         "3. Shelf 2: Features an assortment of biscuits, cookies, and breakfast items, such as Butter cookies, cookie sandwich, Choco Mallows, House of Polvoron (polvoron and soft cookies), Pepero, Ritz crackers, Ube-filled crackers, Hansel Crackers, Fita Crackers, cereals (Koko Krunch, Gold Corn Flakes, Honey Stars, Choco Crunchies), and Mamon.\n"
#                         "4. Shelf 3: Features various snacks and junk food, including cracker nuts, pretzel twists, and trail mix.\n"
#                         "5. Shelf 4: Features a selection of nuts and corn-based snacks like Mixed nuts, toasted peanuts, cornick, Boy Bawang, Ding Dong, Sugo, and Growers.\n"
#                         "6. Shelf 5: Features an assortment of biscuits, cookies, and breakfast items, such as Butter cookies, cookie sandwich, Choco Mallows, House of Polvoron (polvoron and soft cookies), Pepero, Ritz crackers, Ube-filled crackers, Hansel Crackers, Fita Crackers, cereals (Koko Krunch, Gold Corn Flakes, Honey Stars, Choco Crunchies), and Mamon (similar to Shelf 2).\n"
#                         "7. Shelf 6: Features a range of canned goods, including meats (meat loaf, beef loaf, corned beef), fish (tuna, sardines, fried sardines, corned tuna), pork & beans, Shiitake mushroom slices, mushroom pieces & stems, and tomato sauce.\n"
#                         "8. Shelf 7: Features various types of chips and savory snacks, such as potato chips, corn chips, waffle fries, shoestring potatoes, and prawn crackers.\n"
#                         "9. Shelf 8: Features a general selection of junk food and snacks.\n"
#                         "10. Shelf 9: Features dairy products such as milk, processed cheese, yoghurt, and yoghurt drinks, alongside popcorn.\n"
#                         "11. Shelf 10: Features dairy products such as milk, processed cheese, yoghurt, and yoghurt drinks, alongside popcorn (similar to Shelf 9).\n"
#                         "12. Shelf 11: Features instant meals like cup noodles, instant noodles, instant ramen, chocolate rice porridge mix, and instant soup.\n"
#                         "13. Shelf 12: Features instant meals like cup noodles, instant noodles, instant ramen, chocolate rice porridge mix, and instant soup (similar to Shelf 11).\n"
#                         "14. Shelves 13-16: Feature a wide array of beverages, including bottled water, fruit juices, energy drinks, tonic drinks, and other soft drinks.\n\n"
#                         "**Top-down View of the Store**:\n"
#                         "1. From the starting point, Shelf 1, Shelves 13-16, and the counter are immediately visible.\n"
#                         "2. From the starting point: Panning left or moving slightly forward reveals Shelf 1 and its contents. Panning right shows the counter with the cash register.\n"
#                         "3. Moving directly forward from the starting point brings Shelves 13-16 and their products into view. From this position, a side view of Shelf 4 is also visible.\n"
#                         "4. Moving backward from the starting point and panning left reveals a side view of Shelf 3 and its contents.\n"
#                         "5. When near Shelves 13-16, panning left allows viewing of Shelf 4, along with portions of Shelves 8, 11, and 12.\n"
#                         "6. Positioned between Shelves 4 and 8, both Shelf 2 and Shelf 5, along with their items, are visible.\n"
#                         "7. Approaching Shelves 11 and 12 and panning left will reveal parts of Shelves 6, 9, and 10.\n"
#                         "8. As you move closer to Shelves 9 and 10, items on Shelf 7 become visible.\n"
#                         "9. Shelf 2 is behind (or at the back) of Shelf 1, while Shelves 3 and 4 are both adjacent to Shelves 1 and 2. To go to Shelf 2 (and by extension Shelf 5), head towards the midpoint of Shelves 12 and 13-14. Pan left and you will see an aisle that leads to Shelf 2 and 5. You should also see Shelf 4 and 8 when you pan left.\n"
#                         "10. Shelf 8 is on the opposite side of Shelf 12.\n"
#                         "11. Shelf 6 is directly opposite Shelves 9 and 10. So if you see Shelves 9 or 10, move forward and pan left/right to see Shelf 6.\n"
#                         "12. Shelf 5 is adjacent to Shelf 8, so when you see Shelf 8, move towards the aisle between Shelves 4 and 8, move further down the aisle, and you will see Shelf 5 (along with Shelf 2).\n"
#                         "13. Shelf 3 is on the left side of Shelf 1 (if you are facing Shelf 1). If you are at the starting point, you can pan left, move forward a bit, then pan right to see Shelf 3.\n"
#                         "14. Shelf 4 is on the opposite side of Shelf 13-14.\n"
#                         "15. Shelf 7 is a few steps to the right of Shelf 3 (if you are facing Shelf 3). If you see the aisle of Shelf 3, move forward a bit, then pan right to see Shelf 7.\n\n"
#                         "**Fast Tracking** (use this to guide you quickly to the target object):\n"
#                         "- Shelves 13 & 14 have the same target position -> translation: (6.28, 1.36, 8.0), rotation: (0.0, 359.46, 0)\n"
#                         "- Shelves 15 & 16 have the same target position -> translation: (7.9, 1.36, 7.92), rotation: (0.0, 359.46, 0.0)\n"
#                         "- Shelf 1 has the target position -> translation: (7.55, 1.37, 3.7), rotation: (0.0, 269.46, 0.0)\n"
#                         "- Shelf 3 has the target position -> translation: (5.28, 1.37, 0.13), rotation: (0.0, 359.46, 0.0)\n"
#                         "- Shelf 4 has the target position -> translation: (5.34, 1.37, 7.37), rotation: (0.0, 179.46, 0.0)\n"
#                         "- Shelf 2 has the target position -> translation: (4.02, 1.37, 3.66), rotation: (0.0, 89.46, 0.0)\n"
#                         "- Shelf 5 has the target position -> translation: (4.52, 1.37, 3.57), rotation: (0.0, 269.46, 0.0)\n"
#                         "- Shelf 8 has the target position -> translation: (2.94, 1.37, 7.41), rotation: (0.0, 179.46, 0.0)\n"
#                         "- Shelf 12 has the target position -> translation: (2.97, 1.37, 8.21), rotation: (0.0, 359.46, 0.0)\n"
#                         "- Shelf 11 has the target position -> translation: (1.76, 1.37, 6.96), rotation: (0.0, 269.46, 0.0)\n"
#                         "- Shelf 6 has the target position -> translation: (1.54, 1.37, 3.67), rotation: (0.0, 89.46, 0.0)\n"
#                         "- Shelf 10 has the target position -> translation: (2.03, 1.37, 2.85), rotation: (0.0, 269.46, 0.0)\n"
#                         "- Shelf 9 has the target position -> translation: (2.04, 1.37, 1.65), rotation: (0.0, 269.46, 0.0)\n"
#                         "- Shelf 7 has the target position -> translation: (3.0, 1.37, 0.18), rotation: (0.0, 359.46, 0.0)\n\n"
#                         "**Aisle Corridors** (navigable lanes — use these to plan paths):\n"
#                         "- Right wall corridor: x∈[8.5,10.0], z∈[0,9] — starting point area, near counter and Shelf 1\n"
#                         "- Front wall corridor: z∈[0,1.0], x∈[0,9] — along front, near Shelves 3 & 7\n"
#                         "- Left wall corridor: x∈[0,1.0], z∈[0,9] — along left wall\n"
#                         "- Main central aisle: x∈[5.8,7.0], z∈[0.5,8] — between Shelf 3/4/13-14 cluster and Shelf 1\n"
#                         "- Mid-depth aisle: z∈[4.5,6.5], x∈[1,8] — between middle shelf row (z≈3.7) and back cluster (z≈7)\n"
#                         "- Back wall corridor: z∈[8.7,9.5], x∈[0,9]\n\n"
#                         "**Shelf Footprints** (approximate bounding boxes — avoid placing waypoints inside these):\n"
#                         "- Shelf 1: x∈[7.0,8.1], z∈[3.2,4.2]\n"
#                         "- Shelf 2: x∈[3.5,4.6], z∈[3.2,4.2]\n"
#                         "- Shelf 3: x∈[4.8,5.8], z∈[0.0,0.6]\n"
#                         "- Shelf 4: x∈[4.8,5.8], z∈[6.9,7.9]\n"
#                         "- Shelf 5: x∈[4.0,5.1], z∈[3.1,4.1]\n"
#                         "- Shelf 6: x∈[1.0,2.1], z∈[3.2,4.2]\n"
#                         "- Shelf 7: x∈[2.5,3.6], z∈[0.0,0.7]\n"
#                         "- Shelf 8: x∈[2.4,3.5], z∈[6.9,7.9]\n"
#                         "- Shelf 9: x∈[1.5,2.6], z∈[1.2,2.2]\n"
#                         "- Shelf 10: x∈[1.5,2.6], z∈[2.4,3.4]\n"
#                         "- Shelf 11: x∈[1.3,2.3], z∈[6.5,7.5]\n"
#                         "- Shelf 12: x∈[2.5,3.5], z∈[7.7,8.7]\n"
#                         "- Shelves 13-14: x∈[5.8,6.8], z∈[7.5,8.5]\n"
#                         "- Shelves 15-16: x∈[7.4,8.5], z∈[7.4,8.4]\n"
#                         "- Counter: x∈[8.5,10.0], z∈[0.0,3.0]\n\n")

# ========= Layout 2 =========
BASE_SEMANTIC_MEMORY = ("This semantic memory outlines the store's environment, detailing its layout, item locations, and general product descriptions.\n\n"
                        "**Layout of the Store**:\n"
                        "1. Counter: Situated near Shelf 1 and 9, this area includes a cash register.\n"
                        "2. Shelf 1: Features a variety of snacks and junk food, including Pringles, potato chips, cheese rings, Tostitos, Clover Chips, corn chips, Prawn Crackers, Kang-Kong Chips, and Pik-Nik Shoestring Potatoes.\n"
                        "3. Shelf 2: Features an assortment of biscuits, cookies, and breakfast items, such as Butter cookies, cookie sandwich, Choco Mallows, House of Polvoron (polvoron and soft cookies), Pepero, Ritz crackers, Ube-filled crackers, Hansel Crackers, Fita Crackers, cereals (Koko Krunch, Gold Corn Flakes, Honey Stars, Choco Crunchies), and Mamon.\n"
                        "4. Shelf 3: Features various snacks and junk food, including Pringles, potato chips, corn chips, pretzel twists, and trail mix.\n"
                        "5. Shelf 4: Features a selection of nuts and corn-based snacks like Mixed nuts, toasted peanuts, corn.\n"
                        "6. Shelf 5: Features a range of canned goods, including meats (meat loaf, beef loaf, corned beef), fish (tuna, sardines, fried sardines, corned tuna), pork & beans, Shiitake mushroom slices, mushroom pieces & stems, and tomato sauce.\n"
                        "7. Shelf 6: Features a range of canned goods, including meats (meat loaf, beef loaf, corned beef), fish (tuna, sardines, fried sardines, corned tuna), pork & beans, Shiitake mushroom slices, mushroom pieces & stems, and tomato sauce (similar to Shelf 5).\n"
                        "8. Shelf 7: Features instant meals like cup noodles, instant noodles, instant ramen.\n"
                        "9. Shelf 8: Features instant meals like cup noodles, instant noodles, instant ramen (similar to Shelf 7).\n"
                        "10. Shelf 9: Features instant meals like cup noodles, instant noodles, instant ramen (similar to Shelf 7 and 8).\n"
                        "11. Shelf 10: Features a mix of instant noodles, instant ramen, and junk food items.\n"
                        "12. Shelf 11: Features a variety of snacks and junk food, including Pringles, potato chips, corn chips, cheese rings, pretzel twists, and etc.\n"
                        "13. Shelf 12: Features bottled water only.\n"
                        "14. Shelf 13: Features fruit juices only.\n"
                        "15. Shelves 15-16: Feature a wide array of beverages, including energy drinks, tonic drinks, and other soft drinks.\n"
                        "16. Shelf 17: Features dairy products such as milk, processed cheese, yoghurt, and yoghurt drinks, alongside popcorn.\n"
                        "17. Shelf 18: Features instant meals chocolate rice porridge mix and instant soup.\n\n"
                        "**Top-down View of the Store**:\n"
                        "1. From the starting point, Shelves 9-11 are visible, along with the counter. Portions of Shelves 1 and 3 are also visible.\n"
                        "2. Shelf 2 is behind Shelf 1 (likewise, Shelf 1 is behind Shelf 2). Shelves 3 and 4 are adjacent to Shelves 1 and 2.\n"
                        "3. Shelf 5 is along the same aisle as Shelf 2.\n"
                        "4. Shelf 6 is behind Shelf 5 (likewise, Shelf 5 is behind Shelf 6). Shelves 7 and 8 are adjacent to Shelves 5 and 6.\n"
                        "5. Shelves 12-16 are along the same aisle as Shelf 6, which are directly opposite to it.\n"
                        "6. Shelf 17 is along the same aisle as Shelf 12-16, directly beside Shelf 16.\n"
                        "7. Shelves 9-11 are literally on the same side as the counter.\n"
                        "8. Going to Shelf 4 and 8 from the starting point requires you to pan right until you see the end of Shelf 1, then move forward for some distance until you see the aisle that leads to Shelf 4 and 8.\n\n"
                        "**Fast Tracking** (use this to guide you quickly to the target object):\n"
                        "- Shelf 1 has the target position -> translation: (5.01, 1.36, 1.42), rotation: (0.0, 358.83, 0.0)\n"
                        "- Shelf 4 has the target position -> translation: (8.72, 1.36, 3.1), rotation: (0.0, 268.83, 0.0)\n"
                        "- Shelf 2 has the target position -> translation: (5.01, 1.36, 4.56), rotation: (0.0, 178.83, 0.0)\n"
                        "- Shelf 3 has the target position -> translation: (1.18, 1.36, 3.13), rotation: (0.0, 88.83, 0.0)\n"
                        "- Shelf 5 has the target position -> translation: (4.95, 1.36, 3.9), rotation: (0.0, 358.83, 0.0)\n"
                        "- Shelf 8 has the target position -> translation: (8.76, 1.36, 5.27), rotation: (0.0, 271.33, 0.0)\n"
                        "- Shelf 6 has the target position -> translation: (5.0, 1.36, 6.62), rotation: (0.0, 178.83, 0.0)\n"
                        "- Shelf 7 has the target position -> translation: (1.32, 1.36, 5.28), rotation: (0.0, 91.33, 0.0)\n"
                        "- Shelf 9 has the target position -> translation: (1.5, 1.36, 3.29), rotation: (0.0, 268.83, 0.0)\n"
                        "- Shelf 10 has the target position -> translation: (1.47, 1.36, 4.89), rotation: (0.0, 268.83, 0.0)\n"
                        "- Shelf 11 has the target position -> translation: (1.54, 1.36, 6.7), rotation: (0.0, 268.83, 0.0)\n"
                        "- Shelves 12-13 have the same target position -> translation: (2.46, 1.36, 6.15), rotation: (0.0, 358.83, 0.0)\n"
                        "- Shelves 14-15 have the same target position -> translation: (4.26, 1.36, 6.09), rotation: (0.0, 358.83, 0.0)\n"
                        "- Shelf 16 has the target position -> translation: (6.16, 1.36, 6.04), rotation: (0.0, 358.83, 0.0)\n"
                        "- Shelf 17 has the target position -> translation: (7.76, 1.36, 6.08), rotation: (0.0, 358.83, 0.0)\n\n"
                        "**Aisle Corridors** (navigable lanes — use these to plan paths):\n"
                        "- Left wall corridor: x∈[0,1.0], z∈[0,9] — starting point area, near counter and Shelves 3/9\n"
                        "- Front wall corridor: z∈[0,1.0], x∈[0,9] — along front\n"
                        "- Central aisle A: x∈[2.0,4.4], z∈[1,5.5] — between left cluster and middle column (Shelves 1/2/5/6)\n"
                        "- Central aisle B: x∈[5.5,8.2], z∈[1,5.5] — between middle column and right cluster (Shelves 4/8)\n"
                        "- Back wall corridor: z∈[7.2,9.0], x∈[0,9] — behind z≈6 back shelf row\n\n"
                        "**Shelf Footprints** (approximate bounding boxes — avoid placing waypoints inside these):\n"
                        "- Shelf 1: x∈[4.5,5.5], z∈[1.0,1.9]\n"
                        "- Shelf 2: x∈[4.5,5.5], z∈[4.1,5.1]\n"
                        "- Shelf 3: x∈[0.7,1.7], z∈[2.7,3.6]\n"
                        "- Shelf 4: x∈[8.2,9.3], z∈[2.6,3.6]\n"
                        "- Shelf 5: x∈[4.4,5.5], z∈[3.4,4.4]\n"
                        "- Shelf 6: x∈[4.5,5.5], z∈[6.1,7.1]\n"
                        "- Shelf 7: x∈[0.8,1.8], z∈[4.8,5.8]\n"
                        "- Shelf 8: x∈[8.2,9.3], z∈[4.8,5.8]\n"
                        "- Shelf 9: x∈[1.0,2.0], z∈[2.8,3.8]\n"
                        "- Shelf 10: x∈[0.9,2.0], z∈[4.4,5.4]\n"
                        "- Shelf 11: x∈[1.0,2.1], z∈[6.2,7.2]\n"
                        "- Shelves 12-13: x∈[1.9,3.0], z∈[5.7,6.7]\n"
                        "- Shelves 14-15: x∈[3.7,4.8], z∈[5.6,6.6]\n"
                        "- Shelf 16: x∈[5.7,6.7], z∈[5.6,6.5]\n"
                        "- Shelf 17: x∈[7.3,8.3], z∈[5.6,6.6]\n"
                        "- Counter: x∈[0,2.5], z∈[0,1.5]\n\n")

# # ========= Layout 3 =========
# BASE_SEMANTIC_MEMORY = ("This semantic memory outlines the store's environment, detailing its layout, item locations, and general product descriptions.\n\n"
#                         "**Layout of the Store**:\n"
#                         "1. Counter: Situated near Shelves 1 and 2, and beside Shelves 7-8, this area includes a cash register.\n"
#                         "2. Shelf 1: Features instant meals like cup noodles, instant noodles, instant ramen, chocolate rice porridge mix, and instant soup.\n"
#                         "3. Shelf 2: Features canned goods, including meats (meat loaf, beef loaf, corned beef), fish (tuna, sardines, fried sardines, corned tuna), pork & beans, Shiitake mushroom slices, mushroom pieces & stems, and tomato sauce.\n"
#                         "4. Shelf 3: Features a variety of snacks and junk food, including Pringles, potato chips, corn chips, cheese rings, pretzel twists, and etc.\n"
#                         "5. Shelf 4: Features a selection of nuts like Mixed nuts, toasted peanuts, cashews, and green peas.\n"
#                         "6. Shelf 5: Features a selection of nuts like Mixed nuts, toasted peanuts, cashews, and green peas (similar to Shelf 4).\n"
#                         "7. Shelf 6: Features cereals, breakfast items, and biscuits, such as Butter cookies, cookie sandwich, Choco Mallows, House of Polvoron (polvoron and soft cookies), Pepero, Ritz crackers, Ube-filled crackers, Hansel Crackers, Fita Crackers, cereals (Koko Krunch, Gold Corn Flakes, Honey Stars, Choco Crunchies), and Mamon.\n"
#                         "8. Shelf 7: Features bottled water only.\n"
#                         "9. Shelf 8: Features fruit juices only.\n"
#                         "10. Shelf 9: Features a variety of beverages, including energy drinks, tonic drinks, soft drinks, and dairy products such as milk, processed cheese, yoghurt, and yoghurt drinks, alongside popcorn.\n\n"
#                         "**Top-down View of the Store**:\n"
#                         "1. From the starting point, Shelves 1-2 and the counter are immediately visible.\n"
#                         "2. Moving several steps forward from the starting point and panning right should reveal Shelves 7-9 because they are adjacent to the counter.\n"
#                         "3. Moving towards Shelves 7-9 and panning right will reveal Shelf 6.\n"
#                         "4. Shelf 3 is behind Shelf 2 (likewise, Shelf 2 is behind Shelf 3). Shelves 4 and 5 are adjacent to Shelves 2 and 3.\n"
#                         "5. Shelf 5 is facing Shelf 7.\n"
#                         "6. Moving towards Shelf 6 and panning right will reveal Shelf 3.\n"
#                         "7. From the starting point, panning right will reveal Shelf 4, and a portion of Shelf 6.\n"
#                         "**Fast Tracking** (use this to guide you quickly to the target object):\n"
#                         "- Shelf 1 has the target position -> translation: (1.51, 1.36, 3.37), rotation: (0.0, 270.0, 0.0)\n"
#                         "- Shelf 2 has the target position -> translation: (1.52, 1.36, 3.96), rotation: (0.0, 90.0, 0.0)\n"
#                         "- Shelf 4 has the target position -> translation: (2.9, 1.36, 0.33), rotation: (0.0, 357.5, 0.0)\n"
#                         "- Shelf 3 has the target position -> translation: (4.38, 1.36, 3.88), rotation: (0.0, 270.0, 0.0)\n"
#                         "- Shelf 6 has the target position -> translation: (4.38, 1.36, 3.68), rotation: (0.0, 90.0, 0.0)\n"
#                         "- Shelf 5 has the target position -> translation: (3.01, 1.36, 7.65), rotation: (0.0, 180.0, 0.0)\n"
#                         "- Shelves 7-8 have the same target position -> translation: (3.4, 1.36, 7.15), rotation: (0.0, 0.0, 0.0)\n"
#                         "- Shelf 9 has the target position -> translation: (4.8, 1.36, 7.15), rotation: (0.0, 0.0, 0.0)\n\n"
#                         "**Aisle Corridors** (navigable lanes — use these to plan paths):\n"
#                         "- Entrance corridor: x∈[0,6], z∈[0,1.0] — in front of Shelves 1 & 2, near starting point\n"
#                         "- Central aisle A: x∈[1.8,2.5], z∈[1.0,7.5] — runs between Shelves 1/2 and Shelves 3/6\n"
#                         "- Central aisle B: x∈[3.4,4.0], z∈[1.0,7.5] — runs between Shelves 3/6 and Shelves 4/5\n"
#                         "- Back corridor: x∈[0,6], z∈[7.5,9.0] — behind Shelves 5/7/8/9\n"
#                         "- Right corridor: x∈[4.5,6.0], z∈[0,9.0] — runs along right wall past Shelves 7/8/9\n\n"
#                         "**Shelf Footprints** (approximate bounding boxes — avoid placing waypoints inside these):\n"
#                         "- Shelf 1: x∈[0.8,1.8], z∈[3.0,4.0]\n"
#                         "- Shelf 2: x∈[0.8,1.8], z∈[3.7,4.8]\n"
#                         "- Shelf 3: x∈[3.8,4.8], z∈[3.4,4.2]\n"
#                         "- Shelf 4: x∈[2.3,3.4], z∈[0.0,0.8]\n"
#                         "- Shelf 5: x∈[2.5,3.5], z∈[7.2,8.1]\n"
#                         "- Shelf 6: x∈[3.8,4.8], z∈[3.2,4.2]\n"
#                         "- Shelves 7-8: x∈[2.8,4.0], z∈[6.7,7.6]\n"
#                         "- Shelf 9: x∈[4.2,5.4], z∈[6.7,7.6]\n"
#                         "- Counter: x∈[0.5,2.5], z∈[0.0,1.5]\n\n")